version: "3"

services:
  mongo:
    container_name: viz-mongo
    image: mongo
    ports:
      - 27017:27017
    restart: always
  minio:
    container_name: viz-minio
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --address ":9000" --console-address ":9001"
    restart: always
